= Cahier De Recette - DailyBankApp
:toc:
:toc-title: Sommaire

:Entreprise: DailyBank
:Equipe:  

Créé par : 
Créé pour :  

 



== I. Introduction
=== 1. Objet :
[.text-justify]
Ce document a été produit dans le cadre d'un projet d'élaboration d'une application bancaire pour ...


== II. Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. *À vérifier*


=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiés dans la *documentation technique*.


=== 2. Environnement de test :
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== III. Cas de test :
=== 1. Fonctionnalités des guichetiers :
==== 1.1 Gestion des clients :

|====

>|Cas de test 4+|Test-01-01-01
>|Titre 4+|Création d'un nouveau client
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau client

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur le bouton "Nouveau client". ^|La fenêtre de création des clients s'ouvre. ^| aucune ^|OK
^|All_G_C.2 ^|Compléter les champs spécifiés et valider. ^|Un nouveau client est créé. ^|aucune ^|OK


5+|

5+|Commentaire :
Compléter et si on ne valide pas, ...
|====


|====

>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Modification d'un client
>|Objectif 4+| Vérifier qu'il est possible de modifier un client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.3 ^|Cliquer sur le bouton "Modifier client". ^|La fenêtre de modification des données du clients s'ouvre. ^|Le client est sélectionné ^|OK
^|All_G_C.4 ^|Modifier les champs souhaités et confirmer. ^|Retour sur les informations du client. Le client est modifié. ^|La fenêtre modifier client est active ^|OK
^|All_G_C.5 ^|Modifier les champs souhaités et annuler. ^|Retour sur les informations du client. Le client est inchangé. ^|La fenêtre modifier client est active ^|OK

|====


==== 1.2 Gestion des comptes bancaires :


|====

>|Cas de test 4+|Test-01-02-01
>|Titre 4+|Consultation d'un compte
>|Objectif 4+| Vérifier qu'il est possible de consulter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné ^|OK
^|All_G_CB.2 ^|Sélectionner le bouton "Voir opérations". ^|La page des opérations du compte s’affiche. ^|Un compte actif est sélectionné ^|OK
...

|====

|====

>|Cas de test 4+|Test-01-02-02 EVAN
>|Titre 4+|Créer un compte
>|Objectif 4+| Vérifier qu'il est possible de créer un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|CC.0 ^|J’appuie sur le bouton "créer compte". ^|La fenêtre de modification du compte s’ouvre. ^|aucune ^|OK
^|CC.1 ^|Je rentre les données et appuie sur valider. ^|Client créé et redirection sur la gestion de compte. ^|Rentrer des données valide. ^|OK
^|CC.2 ^|J’appuie sur annuler. ^|Client non créée et redirection sur la gestion des comptes. ^|aucune ^|OK


|====

|====

>|Cas de test 4+|Test-01-02-03 EVAN
>|Titre 4+|Clotûter un compte
>|Objectif 4+| Vérifier qu'il est possible de clotûrer un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|CLC.0 ^|je clique sur cloturé compte. ^|Pop-up validation + Le compte est cloturé ^|Un compte actif est sélectionné + Solde = 0 ^|OK

5+|

5+|Commentaire : Si le soldes n'est pas égal à 0 alors un message d'alerte vous indiqueras que vous ne pouvez pas clotûter le compte|

|====


==== 1.3 Gestion des opérations :

|====

>|Cas de test 4+|Test-01-03-01 EVAN
>|Titre 4+|Gestion des opération
>|Objectif 4+| Vérifier qu'il est possible d'accéder à la gestion des opération

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|GO.0 ^|J’appuie sur "Voir Opération". ^|La fenêtre de gestion des opérations s’ouvre. ^|Sélectionner un compte ^|OK


|====

|====

>|Cas de test 4+|Test-01-03-02 EVAN
>|Titre 4+|Débiter un compte
>|Objectif 4+| Vérifier qu'il est possible de débiter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Enregistrer Débit". ^|La page des débit du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros
 ^|OK
^|All_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
 ^|OK
^|All_G_COP.4  ^|Rentrer un montant 250 dans le champ "Montant". ^|Blocage ! + pop-up ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
 ^|OK
  
 

|====

|====

>|Cas de test 4+|Test-01-03-03 EVAN
>|Titre 4+|Créditer un compte
>|Objectif 4+| Vérifier qu'il est possible de créditer un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|GO_C.0 ^|Je clique sur "Enregistrer Crédit" . ^|La fenêtre d’opération crédit s’ouvre. ^|Le compte sélectionné est actif. ^|OK
^|GO_C.1 ^|Je rentre un montant de 100 ^|le nouveau solde est de +50 par rapport à avant. ^|Aucune ^|OK
^|GO_C.2 ^|J’appuie sur annuler. ^|L’opération est annulé, retour sur la fenêtre de gestion d’opération. ^|aucune ^|OK


|====

|====

>|Cas de test 4+|Test-01-03-04 EVAN
>|Titre 4+|Virement compte à compte
>|Objectif 4+| Vérifier qu'il est possible de faire un virement

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|GO_V.0 ^|Je clique sur "Enregistrez Virement" . ^|La fenêtre d’opération virement s’ouvre. ^|Le compte sélectionné est actif. ^|OK
^|GO_V.1 ^|Je rentre un numéro de compte valide et un montant valide ^|le transfert est effectué et est affiché sur les 2 compte, la fenêtre la fenêtre de gestion d’opération s’ouvre.  ^|aucune ^|OK

5+|

5+|Commentaire : Veuillez rentrez un numéro de compte existant ainsi qu'un montant positif.|

|====

==== 1.4 Gestion des Prélèvements :

|====

>|Cas de test 4+|Test-01-03-01 EVAN
>|Titre 4+|Gestion prélevement
>|Objectif 4+| Vérifier qu'il est possible d'acceder à la gestion des prélèvements

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|GP.0 ^|Cliquer sur "gestion" puis "Prélèvement". ^|Ouverture page gestion des prélèvements ^|être connecté en tant que guichetier ou chef d’agence ^|OK

5+|

5+|Commentaire : Aucun.  |

|====

|====

>|Cas de test 4+|Test-01-03-02 EVAN
>|Titre 4+|Créer un prélèvement
>|Objectif 4+| Vérifier qu'il est possible de créer un prélèvement

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|CP.0 ^|cliquer sur "nouveau Prélèvement". ^|Ouverture page de création de prélèvement ^|aucune ^|OK
^|CP.1 ^|Remplir tout les champs puis valider. ^|Ajout du prélèvement et retour sur la page de gestion des prélèvements  ^|Champs tous valide ^|OK
^|CP.2 ^|Cliquer sur "annuler" . ^|Annulation de la création du prelevement + retour sur la page de gestion des prélèvement.  ^|aucune ^|OK

5+|

5+|Commentaire : Veuillez rentrer un numéro de compte existant, la date est le numéro du jour entre (1 et 28).  |

|====








=== 2. Fonctionnalités des chefs d'agence :
[.text-justify]
Les chefs d'agence ont accès aux mêmes fonctionnalités que les guichetiers, ainsi que d'autres qui leur sont réservées.

==== 2.1 Gestion des clients :

|====

>|Cas de test 4+|Test-02-01-01
>|Titre 4+|Rendre inactif un client
>|Objectif 4+| Vérifier qu'il est possible de rendre un client inactif

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ... ^| ...

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

==== 2.2 Simulation Emprunt, Assurance:

|====

>|Cas de test 4+|Test-02-02-01 EVAN
>|Titre 4+|Simuler un emprunt
>|Objectif 4+| Vérifier qu'il est possible de simuler un emprunt

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|SE.0 ^|Cliquer sur Simulation puis emprunt. ^|Ouverture de la page de configuration d’emprunt.  ^|être connecté en tant que chef d’agence ^| OK
^|SE.1 ^|Sélectionner mois et rentrez les chiffres dans les cases puis validez ^|Ouverture d’un tableau d’amortissement d’emprunt en mois. ^|aucune ^| OK
^|SE.2 ^|Sélectionner année et rentrez les chiffres dans les cases puis validez ^|Ouverture d’un tableau d’amortissement d’emprunt en année. ^|aucune ^| OK
^|SE.3 ^|Cliquer sur annuler ^|Retour à la page d’accueil. ^|aucune ^| OK

5+|

5+|Commentaire : Le taux est annuel veuillez rentrez que des chiffres et pour le montant des decimaux sont acceptés.|

|====

|====

>|Cas de test 4+|Test-02-02-01 EVAN
>|Titre 4+|Simuler une Assurance
>|Objectif 4+| Vérifier qu'il est possible de simuler une assurance

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|SA.0 ^|Cliquer sur le bouton assurance ^|affichage d’une zone de texte  ^|Aucune ^| OK
^|SA.1 ^|Recliquer sur le bouton assurance ^|Suppression de la zone de texte ^|avoir appuyé une fois sur ce bouton ^| OK
^|SA.2 ^|Rentrez un chiffre et validez ^|Ouverture d’un tableau d’amortissement d’emprunt + prix assurance ^|avoir appuyé sur le bouton ^| OK

5+|

5+|Commentaire : Le taux d'assurance est annuel|

|====